### ISSUE TITLE
a better way to set middleware fn param count?

### ISSUE THREAD

**Issue by mxriverlynn** [alessioalex/generic-middleware#13]
Hi! 

First off, thanks for this great little library. I'm nearly done ripping out my own awful, terrible idea of a middleware implementation in my "rabbus" library and this one has done marvelous wonders for me already.

I do have one minor issue, though, in how i'm using the library.

The way it stands, I am manually adding an empty function to my middleware immediately after instantiating it, to make sure the param count is correct:

``` js
var m = new middleware();
m.use(function(message, properties, actions, next){
  next();
});
```

I have to do this because of the asynchronous nature of my library, and the very real possibility of an error handler being added before the first middleware function (I had this happen in my unit tests, for example).

It's not a huge problem, since I found a workaround as shown above... but it would be nice to have an alternative method to set the param count - perhaps an explicit method to state how many parameters are to be expected?

Thanks!

**Comment by alessioalex** [comment]
Hi @derickbailey ! Glad you found this module useful.

Actually you can already achieve that by using `m._numberOfParams` as commented in the code here: https://github.com/alessioalex/generic-middleware/blob/master/lib/middleware.js#L13-L15

I should probably rename that to `m.numberOfParams` and include it in the public API so that others in your situation might benefit as well.

Quick question(s): Did you develop your own middleware using this as an inspiration or is it used internally in your projects? (I've looked at the dependencies but it's not there)
I'm asking because I'd like to know if I could do something to potentially improve the module.

Edit: to answer my own question, I saw that you have used it in the development module: https://github.com/derickbailey/rabbus/commit/1c5f5b2f06c952c3bcd2dc8440b423a12480a312

**Comment by jokeyrhyme** [comment]
I wonder what a long-term solution to this might look like?
- `#use(fn, arity)` - new parameter so that each middleware can have a different number of arguments, and they are just normalised internally?
- or maybe unify handlers and error handlers so that all middleware have exactly the same number of arguments?
- or maybe split `#use(fn)` so that it is only for handlers, and have a completely separate method to register error handlers?
- or keep `#use(fn)` but add specific `#addHandler(fn)` and `#addErrorHandler(fn)` methods?

Also, while the `#_numberOfParams` property is accessible, it's probably not a good idea to use "private" properties. I'm not sure if we're planning to bump major semver numbers for changes to such properties.

**Comment by alessioalex** [comment]
@jokeyrhyme indeed, I am working on releasing a new version and exposing that as public API. 

@jokeyrhyme @derickbailey I was wrong with my previous example, that won't work because of how this is being proxied inside `generic-middleware/index.js`: https://github.com/alessioalex/generic-middleware/blob/master/index.js#L13-L15

I will make a feature branch and link it here shortly so you can have a look and let me know how you would feel about it. Since this a simple thing though I will most likely expose that as `m.paramsLength` and let the end-users manipulate it. I want to avoid doing things like `#use(fn, arity)` or `#addHandler` because I'd like to keep the API as close to Connect / Express as possible.

**Comment by alessioalex** [comment]
Implemented this properly (readme, example, tests) in a feature branch:
- branch: https://github.com/alessioalex/generic-middleware/tree/params-length
- changes: https://github.com/alessioalex/generic-middleware/commit/947b3767d0bf2fec192ab5178c84bee3a714e81e
- working example: https://github.com/alessioalex/generic-middleware/blob/params-length/examples/set-params-length.js

Let me know what you guys think. / cc @jokeyrhyme @derickbailey 

If it's fine by both I can merge and publish a new major version to NPM.

**Comment by mxriverlynn** [comment]
thanks for the fast response / update on this! :) that branch looks good to me.

i agree with keeping the API close to express - that's one of the reasons i picked this lib to replace my hand-coded junk. 

one thing that just popped into my head... maybe having a method like "setParams" could look like this:

`m.setParams("foo", "bar", "baz") // single params`

or

`m.setMiddlewareParams(["foo", "bar", "baz"]) // array version`

I only suggest this as I'm not terribly fond of "magic numbers" hard coded in things. it would read a little nicer to know why this number exists and what it's doing. having a list of string names would not really do anything other than give a count, though. internally, it would just set the same value, but externally the API looks a bit nicer.

**Comment by mxriverlynn** [comment]
oh, and the dev branch of my rabbus project has the new code w/ the reference to this project. https://github.com/derickbailey/rabbus/tree/dev

if you look through the master branch, at the "rabbus/lib/shire" folder, that's where i had tried to hack together my own... it worked, mostly... but it was really bad. too many concerns in the wrong places, leaky abstractions, duplicated code... blech. 

but my dev branch with generic-middleware has allowed me to greatly clean up the mess. you can see my use in the rabbus/lib/consumer/index.js and rabbus/lib/producer/index.js files.

i still have a lot of cleanup to do, but it's coming along nicely!

**Comment by alessioalex** [comment]
@derickbailey that indeed sounded like a good suggestion since it's better to actually see what you intend to use instead of typing in a magic number. I went ahead and implemented this in the feature branch, see commit here: https://github.com/alessioalex/generic-middleware/commit/4a0be5c822e7ed06149e8037226128bae0ca1b9c

The method is called `setParams` and accepts single params as well as an array.

**Comment by mxriverlynn** [comment]
nice! :) that looks great - will make things a bit simpler for me, for sure. thanks!

**Comment by jokeyrhyme** [comment]
I prefer the `#setParams()` approach too. That way we can still hide the internals.

**Comment by alessioalex** [comment]
@derickbailey @jokeyrhyme great! pushlished version `2.1.0` to npm with this new feature. I've decided to update the minor version and not the major one because there were no breaking changes, only this new functionality added.

**Comment by jokeyrhyme** [comment]
Very semver. Excellent.
